[package]
name = "shared"
rust-version.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
bevy_ecs.workspace = true
bevy_reflect.workspace = true
serde.workspace = true

[features]
reflect = []
